<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>SubnauticaRegenMod</AssemblyName>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="src/game-code/**" />
    <None Include="src/game-code/**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>/libs/subnautica/Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>/libs/subnautica/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>/libs/subnautica/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>/libs/subnautica/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>/libs/subnautica/Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>/libs/subnautica/Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>/libs/bepinex/0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>/libs/bepinex/BepInEx.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
